/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowgestion (void)
{
  GtkWidget *windowgestion;
  GtkWidget *fixed9;
  GtkWidget *buttonmenucp;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image11;
  GtkWidget *label312;
  GtkWidget *notebook6;
  GtkWidget *fixed10;
  GtkWidget *label277;
  GtkWidget *entryid;
  GtkWidget *buttonrecherchrer;
  GtkWidget *image2;
  GtkWidget *scrolledwindow26;
  GtkWidget *viewport1;
  GtkWidget *fixed11;
  GtkWidget *treeview11;
  GtkWidget *buttonsupprimer;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image4;
  GtkWidget *label280;
  GtkWidget *buttonmodifier;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image6;
  GtkWidget *label282;
  GtkWidget *buttonactualiser;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image3;
  GtkWidget *label279;
  GtkWidget *buttonboard;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image7;
  GtkWidget *label283;
  GtkWidget *buttonajouter;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image5;
  GtkWidget *label281;
  GtkWidget *label278;
  GtkWidget *label273;
  GtkWidget *fixed12;
  GtkWidget *entryajoutidentifiant;
  GtkWidget *entryajoutquantite;
  GtkObject *spinbuttonajoutjour_adj;
  GtkWidget *spinbuttonajoutjour;
  GtkObject *spinbuttonajoutmois_adj;
  GtkWidget *spinbuttonajoutmois;
  GtkObject *spinbuttonajoutannee_adj;
  GtkWidget *spinbuttonajoutannee;
  GtkWidget *buttonajout;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image8;
  GtkWidget *label290;
  GtkWidget *labelajoutreus;
  GtkWidget *label286;
  GtkWidget *label287;
  GtkWidget *label285;
  GtkWidget *label288;
  GtkWidget *label289;
  GtkWidget *checkbutton2;
  GtkWidget *label284;
  GtkWidget *comboboxajouttype;
  GtkWidget *radiobutton2;
  GSList *radiobutton2_group = NULL;
  GtkWidget *radiobutton1;
  GtkWidget *label274;
  GtkWidget *fixed13;
  GtkWidget *fixed14;
  GtkWidget *entrymodifquantite;
  GtkObject *spinbuttonmodifjour_adj;
  GtkWidget *spinbuttonmodifjour;
  GtkObject *spinbuttonmodifmois_adj;
  GtkWidget *spinbuttonmodifmois;
  GtkObject *spinbuttonmodifanee_adj;
  GtkWidget *spinbuttonmodifanee;
  GtkWidget *buttonmodif;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image9;
  GtkWidget *label297;
  GtkWidget *labelmodifreus;
  GtkWidget *label291;
  GtkWidget *label293;
  GtkWidget *label296;
  GtkWidget *checkbutton1;
  GtkWidget *comboboxmodiftype;
  GtkWidget *comboboxmodifmarque;
  GtkWidget *label294;
  GtkWidget *label295;
  GtkWidget *label275;
  GtkWidget *fixed15;
  GtkWidget *scrolledwindow27;
  GtkWidget *viewport2;
  GtkWidget *fixed16;
  GtkWidget *treeview12;
  GtkWidget *buttonaffichboard;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image10;
  GtkWidget *label310;
  GtkWidget *label298;
  GtkWidget *label276;

  windowgestion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowgestion), _("stock managment"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (windowgestion), fixed9);

  buttonmenucp = gtk_button_new ();
  gtk_widget_show (buttonmenucp);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonmenucp, 496, 163);
  gtk_widget_set_size_request (buttonmenucp, 136, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonmenucp), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image11 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox9), image11, FALSE, FALSE, 0);

  label312 = gtk_label_new_with_mnemonic (_("Menu principale"));
  gtk_widget_show (label312);
  gtk_box_pack_start (GTK_BOX (hbox9), label312, FALSE, FALSE, 0);

  notebook6 = gtk_notebook_new ();
  gtk_widget_show (notebook6);
  gtk_fixed_put (GTK_FIXED (fixed9), notebook6, 0, 192);
  gtk_widget_set_size_request (notebook6, 648, 488);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook6), fixed10);

  label277 = gtk_label_new_with_mnemonic (_("<b><span foreground =\"gray\">Filtre de recherche :</span></b>"));
  gtk_widget_show (label277);
  gtk_fixed_put (GTK_FIXED (fixed10), label277, 176, 0);
  gtk_widget_set_size_request (label277, 257, 40);
  gtk_label_set_use_markup (GTK_LABEL (label277), TRUE);
  gtk_label_set_justify (GTK_LABEL (label277), GTK_JUSTIFY_CENTER);

  entryid = gtk_entry_new ();
  gtk_widget_show (entryid);
  gtk_fixed_put (GTK_FIXED (fixed10), entryid, 224, 80);
  gtk_widget_set_size_request (entryid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid), 8226);

  buttonrecherchrer = gtk_button_new ();
  gtk_widget_show (buttonrecherchrer);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonrecherchrer, 384, 80);
  gtk_widget_set_size_request (buttonrecherchrer, 32, 29);

  image2 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (buttonrecherchrer), image2);

  scrolledwindow26 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow26);
  gtk_fixed_put (GTK_FIXED (fixed10), scrolledwindow26, 16, 128);
  gtk_widget_set_size_request (scrolledwindow26, 584, 256);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow26), viewport1);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed11);

  treeview11 = gtk_tree_view_new ();
  gtk_widget_show (treeview11);
  gtk_fixed_put (GTK_FIXED (fixed11), treeview11, 0, 0);
  gtk_widget_set_size_request (treeview11, 568, 288);

  buttonsupprimer = gtk_button_new ();
  gtk_widget_show (buttonsupprimer);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonsupprimer, 136, 400);
  gtk_widget_set_size_request (buttonsupprimer, 104, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonsupprimer), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox2), image4, FALSE, FALSE, 0);

  label280 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label280);
  gtk_box_pack_start (GTK_BOX (hbox2), label280, FALSE, FALSE, 0);

  buttonmodifier = gtk_button_new ();
  gtk_widget_show (buttonmodifier);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonmodifier, 384, 400);
  gtk_widget_set_size_request (buttonmodifier, 104, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonmodifier), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox4), image6, FALSE, FALSE, 0);

  label282 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label282);
  gtk_box_pack_start (GTK_BOX (hbox4), label282, FALSE, FALSE, 0);

  buttonactualiser = gtk_button_new ();
  gtk_widget_show (buttonactualiser);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonactualiser, 16, 400);
  gtk_widget_set_size_request (buttonactualiser, 104, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonactualiser), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image3 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox1), image3, FALSE, FALSE, 0);

  label279 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label279);
  gtk_box_pack_start (GTK_BOX (hbox1), label279, FALSE, FALSE, 0);

  buttonboard = gtk_button_new ();
  gtk_widget_show (buttonboard);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonboard, 504, 400);
  gtk_widget_set_size_request (buttonboard, 104, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonboard), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image7 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox5), image7, FALSE, FALSE, 0);

  label283 = gtk_label_new_with_mnemonic (_("Board"));
  gtk_widget_show (label283);
  gtk_box_pack_start (GTK_BOX (hbox5), label283, FALSE, FALSE, 0);

  buttonajouter = gtk_button_new ();
  gtk_widget_show (buttonajouter);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonajouter, 256, 400);
  gtk_widget_set_size_request (buttonajouter, 104, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonajouter), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox3), image5, FALSE, FALSE, 0);

  label281 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label281);
  gtk_box_pack_start (GTK_BOX (hbox3), label281, FALSE, FALSE, 0);

  label278 = gtk_label_new (_("veuillez saisir l'identifiant du produit :"));
  gtk_widget_show (label278);
  gtk_fixed_put (GTK_FIXED (fixed10), label278, 192, 48);
  gtk_widget_set_size_request (label278, 264, 24);

  label273 = gtk_label_new (_("Page principale"));
  gtk_widget_show (label273);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 0), label273);
  gtk_label_set_justify (GTK_LABEL (label273), GTK_JUSTIFY_CENTER);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (notebook6), fixed12);

  entryajoutidentifiant = gtk_entry_new ();
  gtk_widget_show (entryajoutidentifiant);
  gtk_fixed_put (GTK_FIXED (fixed12), entryajoutidentifiant, 312, 104);
  gtk_widget_set_size_request (entryajoutidentifiant, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryajoutidentifiant), 8226);

  entryajoutquantite = gtk_entry_new ();
  gtk_widget_show (entryajoutquantite);
  gtk_fixed_put (GTK_FIXED (fixed12), entryajoutquantite, 312, 208);
  gtk_widget_set_size_request (entryajoutquantite, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryajoutquantite), 8226);

  spinbuttonajoutjour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonajoutjour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonajoutjour_adj), 1, 0);
  gtk_widget_show (spinbuttonajoutjour);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbuttonajoutjour, 304, 256);
  gtk_widget_set_size_request (spinbuttonajoutjour, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbuttonajoutjour), TRUE);

  spinbuttonajoutmois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonajoutmois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonajoutmois_adj), 1, 0);
  gtk_widget_show (spinbuttonajoutmois);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbuttonajoutmois, 384, 256);
  gtk_widget_set_size_request (spinbuttonajoutmois, 60, 27);

  spinbuttonajoutannee_adj = gtk_adjustment_new (2021, 2021, 2121, 1, 10, 10);
  spinbuttonajoutannee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonajoutannee_adj), 1, 0);
  gtk_widget_show (spinbuttonajoutannee);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbuttonajoutannee, 464, 256);
  gtk_widget_set_size_request (spinbuttonajoutannee, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbuttonajoutannee), TRUE);

  buttonajout = gtk_button_new ();
  gtk_widget_show (buttonajout);
  gtk_fixed_put (GTK_FIXED (fixed12), buttonajout, 232, 400);
  gtk_widget_set_size_request (buttonajout, 128, 45);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonajout), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox6), image8, FALSE, FALSE, 0);

  label290 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label290);
  gtk_box_pack_start (GTK_BOX (hbox6), label290, FALSE, FALSE, 0);

  labelajoutreus = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (labelajoutreus);
  gtk_fixed_put (GTK_FIXED (fixed12), labelajoutreus, 144, 312);
  gtk_widget_set_size_request (labelajoutreus, 320, 56);
  gtk_label_set_use_markup (GTK_LABEL (labelajoutreus), TRUE);

  label286 = gtk_label_new (_("identifiant :"));
  gtk_widget_show (label286);
  gtk_fixed_put (GTK_FIXED (fixed12), label286, 88, 112);
  gtk_widget_set_size_request (label286, 177, 24);

  label287 = gtk_label_new (_("marque du produit:"));
  gtk_widget_show (label287);
  gtk_fixed_put (GTK_FIXED (fixed12), label287, 88, 160);
  gtk_widget_set_size_request (label287, 161, 24);

  label285 = gtk_label_new (_("type du produit :      "));
  gtk_widget_show (label285);
  gtk_fixed_put (GTK_FIXED (fixed12), label285, 88, 56);
  gtk_widget_set_size_request (label285, 153, 25);

  label288 = gtk_label_new (_("Quantit\303\251 :"));
  gtk_widget_show (label288);
  gtk_fixed_put (GTK_FIXED (fixed12), label288, 104, 208);
  gtk_widget_set_size_request (label288, 150, 24);

  label289 = gtk_label_new (_("Date d'\303\251xpiration :"));
  gtk_widget_show (label289);
  gtk_fixed_put (GTK_FIXED (fixed12), label289, 88, 256);
  gtk_widget_set_size_request (label289, 161, 32);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("valider"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed12), checkbutton2, 112, 288);
  gtk_widget_set_size_request (checkbutton2, 118, 24);

  label284 = gtk_label_new (_("ajoutez vos produits  :"));
  gtk_widget_show (label284);
  gtk_fixed_put (GTK_FIXED (fixed12), label284, 216, 0);
  gtk_widget_set_size_request (label284, 185, 32);

  comboboxajouttype = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxajouttype);
  gtk_fixed_put (GTK_FIXED (fixed12), comboboxajouttype, 312, 56);
  gtk_widget_set_size_request (comboboxajouttype, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxajouttype), _("produit1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxajouttype), _("produit2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxajouttype), _("produit3"));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("marque2"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton2, 440, 152);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("marque1"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton1, 312, 152);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  label274 = gtk_label_new (_("Ajout"));
  gtk_widget_show (label274);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 1), label274);
  gtk_misc_set_alignment (GTK_MISC (label274), 0.5, 0.33);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (notebook6), fixed13);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_fixed_put (GTK_FIXED (fixed13), fixed14, 0, 0);
  gtk_widget_set_size_request (fixed14, 0, 0);

  entrymodifquantite = gtk_entry_new ();
  gtk_widget_show (entrymodifquantite);
  gtk_fixed_put (GTK_FIXED (fixed14), entrymodifquantite, 312, 208);
  gtk_widget_set_size_request (entrymodifquantite, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymodifquantite), 8226);

  spinbuttonmodifjour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonmodifjour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmodifjour_adj), 1, 0);
  gtk_widget_show (spinbuttonmodifjour);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbuttonmodifjour, 304, 256);
  gtk_widget_set_size_request (spinbuttonmodifjour, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbuttonmodifjour), TRUE);

  spinbuttonmodifmois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonmodifmois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmodifmois_adj), 1, 0);
  gtk_widget_show (spinbuttonmodifmois);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbuttonmodifmois, 384, 256);
  gtk_widget_set_size_request (spinbuttonmodifmois, 60, 27);

  spinbuttonmodifanee_adj = gtk_adjustment_new (2021, 2021, 2121, 1, 10, 10);
  spinbuttonmodifanee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmodifanee_adj), 1, 0);
  gtk_widget_show (spinbuttonmodifanee);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbuttonmodifanee, 464, 256);
  gtk_widget_set_size_request (spinbuttonmodifanee, 60, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbuttonmodifanee), TRUE);

  buttonmodif = gtk_button_new ();
  gtk_widget_show (buttonmodif);
  gtk_fixed_put (GTK_FIXED (fixed14), buttonmodif, 232, 400);
  gtk_widget_set_size_request (buttonmodif, 128, 45);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonmodif), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image9 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox7), image9, FALSE, FALSE, 0);

  label297 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label297);
  gtk_box_pack_start (GTK_BOX (hbox7), label297, FALSE, FALSE, 0);

  labelmodifreus = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (labelmodifreus);
  gtk_fixed_put (GTK_FIXED (fixed14), labelmodifreus, 152, 304);
  gtk_widget_set_size_request (labelmodifreus, 320, 56);
  gtk_label_set_use_markup (GTK_LABEL (labelmodifreus), TRUE);

  label291 = gtk_label_new (_("modifiez vos produits  :"));
  gtk_widget_show (label291);
  gtk_fixed_put (GTK_FIXED (fixed14), label291, 216, 0);
  gtk_widget_set_size_request (label291, 185, 32);

  label293 = gtk_label_new (_("Type du produit  :      "));
  gtk_widget_show (label293);
  gtk_fixed_put (GTK_FIXED (fixed14), label293, 88, 56);
  gtk_widget_set_size_request (label293, 153, 25);

  label296 = gtk_label_new (_("Date d'\303\251xpiration:"));
  gtk_widget_show (label296);
  gtk_fixed_put (GTK_FIXED (fixed14), label296, 88, 256);
  gtk_widget_set_size_request (label296, 161, 32);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("valider"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed14), checkbutton1, 112, 296);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  comboboxmodiftype = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxmodiftype);
  gtk_fixed_put (GTK_FIXED (fixed14), comboboxmodiftype, 312, 56);
  gtk_widget_set_size_request (comboboxmodiftype, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodiftype), _("produit1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodiftype), _("produit2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodiftype), _("produit3"));

  comboboxmodifmarque = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxmodifmarque);
  gtk_fixed_put (GTK_FIXED (fixed14), comboboxmodifmarque, 312, 136);
  gtk_widget_set_size_request (comboboxmodifmarque, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodifmarque), _("marque 1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodifmarque), _("marque 2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodifmarque), _("marque 3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxmodifmarque), _("marque 4"));

  label294 = gtk_label_new (_("Marque du produits :"));
  gtk_widget_show (label294);
  gtk_fixed_put (GTK_FIXED (fixed14), label294, 88, 136);
  gtk_widget_set_size_request (label294, 161, 24);

  label295 = gtk_label_new (_("Quantit\303\251 :"));
  gtk_widget_show (label295);
  gtk_fixed_put (GTK_FIXED (fixed14), label295, 104, 208);
  gtk_widget_set_size_request (label295, 150, 24);

  label275 = gtk_label_new (_("Modification"));
  gtk_widget_show (label275);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 2), label275);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (notebook6), fixed15);

  scrolledwindow27 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow27);
  gtk_fixed_put (GTK_FIXED (fixed15), scrolledwindow27, 144, 40);
  gtk_widget_set_size_request (scrolledwindow27, 300, 200);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow27), viewport2);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (viewport2), fixed16);

  treeview12 = gtk_tree_view_new ();
  gtk_widget_show (treeview12);
  gtk_fixed_put (GTK_FIXED (fixed16), treeview12, 0, 0);
  gtk_widget_set_size_request (treeview12, 300, 200);

  buttonaffichboard = gtk_button_new ();
  gtk_widget_show (buttonaffichboard);
  gtk_fixed_put (GTK_FIXED (fixed15), buttonaffichboard, 240, 400);
  gtk_widget_set_size_request (buttonaffichboard, 120, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonaffichboard), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image10 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox8), image10, FALSE, FALSE, 0);

  label310 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label310);
  gtk_box_pack_start (GTK_BOX (hbox8), label310, FALSE, FALSE, 0);

  label298 = gtk_label_new (_("Produits hors stock :"));
  gtk_widget_show (label298);
  gtk_fixed_put (GTK_FIXED (fixed15), label298, 136, 0);
  gtk_widget_set_size_request (label298, 312, 32);

  label276 = gtk_label_new (_("Board"));
  gtk_widget_show (label276);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook6), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook6), 3), label276);

  g_signal_connect ((gpointer) buttonmenucp, "clicked",
                    G_CALLBACK (on_buttonmenucp_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonrecherchrer, "clicked",
                    G_CALLBACK (on_buttonrecherchrer_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview11, "row_activated",
                    G_CALLBACK (on_treeview11_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonsupprimer, "clicked",
                    G_CALLBACK (on_buttonsupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifier, "clicked",
                    G_CALLBACK (on_buttonmodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonactualiser, "clicked",
                    G_CALLBACK (on_buttonactualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonboard, "clicked",
                    G_CALLBACK (on_buttonboard_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonajouter, "clicked",
                    G_CALLBACK (on_buttonajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonajout, "clicked",
                    G_CALLBACK (on_buttonajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonmodif, "clicked",
                    G_CALLBACK (on_buttonmodif_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonaffichboard, "clicked",
                    G_CALLBACK (on_buttonaffichboard_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowgestion, windowgestion, "windowgestion");
  GLADE_HOOKUP_OBJECT (windowgestion, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (windowgestion, buttonmenucp, "buttonmenucp");
  GLADE_HOOKUP_OBJECT (windowgestion, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (windowgestion, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (windowgestion, image11, "image11");
  GLADE_HOOKUP_OBJECT (windowgestion, label312, "label312");
  GLADE_HOOKUP_OBJECT (windowgestion, notebook6, "notebook6");
  GLADE_HOOKUP_OBJECT (windowgestion, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (windowgestion, label277, "label277");
  GLADE_HOOKUP_OBJECT (windowgestion, entryid, "entryid");
  GLADE_HOOKUP_OBJECT (windowgestion, buttonrecherchrer, "buttonrecherchrer");
  GLADE_HOOKUP_OBJECT (windowgestion, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowgestion, scrolledwindow26, "scrolledwindow26");
  GLADE_HOOKUP_OBJECT (windowgestion, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (windowgestion, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (windowgestion, treeview11, "treeview11");
  GLADE_HOOKUP_OBJECT (windowgestion, buttonsupprimer, "buttonsupprimer");
  GLADE_HOOKUP_OBJECT (windowgestion, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowgestion, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowgestion, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowgestion, label280, "label280");
  GLADE_HOOKUP_OBJECT (windowgestion, buttonmodifier, "buttonmodifier");
  GLADE_HOOKUP_OBJECT (windowgestion, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowgestion, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowgestion, image6, "image6");
  GLADE_HOOKUP_OBJECT (windowgestion, label282, "label282");
  GLADE_HOOKUP_OBJECT (windowgestion, buttonactualiser, "buttonactualiser");
  GLADE_HOOKUP_OBJECT (windowgestion, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowgestion, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowgestion, image3, "image3");
  GLADE_HOOKUP_OBJECT (windowgestion, label279, "label279");
  GLADE_HOOKUP_OBJECT (windowgestion, buttonboard, "buttonboard");
  GLADE_HOOKUP_OBJECT (windowgestion, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (windowgestion, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (windowgestion, image7, "image7");
  GLADE_HOOKUP_OBJECT (windowgestion, label283, "label283");
  GLADE_HOOKUP_OBJECT (windowgestion, buttonajouter, "buttonajouter");
  GLADE_HOOKUP_OBJECT (windowgestion, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowgestion, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowgestion, image5, "image5");
  GLADE_HOOKUP_OBJECT (windowgestion, label281, "label281");
  GLADE_HOOKUP_OBJECT (windowgestion, label278, "label278");
  GLADE_HOOKUP_OBJECT (windowgestion, label273, "label273");
  GLADE_HOOKUP_OBJECT (windowgestion, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (windowgestion, entryajoutidentifiant, "entryajoutidentifiant");
  GLADE_HOOKUP_OBJECT (windowgestion, entryajoutquantite, "entryajoutquantite");
  GLADE_HOOKUP_OBJECT (windowgestion, spinbuttonajoutjour, "spinbuttonajoutjour");
  GLADE_HOOKUP_OBJECT (windowgestion, spinbuttonajoutmois, "spinbuttonajoutmois");
  GLADE_HOOKUP_OBJECT (windowgestion, spinbuttonajoutannee, "spinbuttonajoutannee");
  GLADE_HOOKUP_OBJECT (windowgestion, buttonajout, "buttonajout");
  GLADE_HOOKUP_OBJECT (windowgestion, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (windowgestion, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (windowgestion, image8, "image8");
  GLADE_HOOKUP_OBJECT (windowgestion, label290, "label290");
  GLADE_HOOKUP_OBJECT (windowgestion, labelajoutreus, "labelajoutreus");
  GLADE_HOOKUP_OBJECT (windowgestion, label286, "label286");
  GLADE_HOOKUP_OBJECT (windowgestion, label287, "label287");
  GLADE_HOOKUP_OBJECT (windowgestion, label285, "label285");
  GLADE_HOOKUP_OBJECT (windowgestion, label288, "label288");
  GLADE_HOOKUP_OBJECT (windowgestion, label289, "label289");
  GLADE_HOOKUP_OBJECT (windowgestion, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (windowgestion, label284, "label284");
  GLADE_HOOKUP_OBJECT (windowgestion, comboboxajouttype, "comboboxajouttype");
  GLADE_HOOKUP_OBJECT (windowgestion, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (windowgestion, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (windowgestion, label274, "label274");
  GLADE_HOOKUP_OBJECT (windowgestion, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (windowgestion, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (windowgestion, entrymodifquantite, "entrymodifquantite");
  GLADE_HOOKUP_OBJECT (windowgestion, spinbuttonmodifjour, "spinbuttonmodifjour");
  GLADE_HOOKUP_OBJECT (windowgestion, spinbuttonmodifmois, "spinbuttonmodifmois");
  GLADE_HOOKUP_OBJECT (windowgestion, spinbuttonmodifanee, "spinbuttonmodifanee");
  GLADE_HOOKUP_OBJECT (windowgestion, buttonmodif, "buttonmodif");
  GLADE_HOOKUP_OBJECT (windowgestion, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (windowgestion, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (windowgestion, image9, "image9");
  GLADE_HOOKUP_OBJECT (windowgestion, label297, "label297");
  GLADE_HOOKUP_OBJECT (windowgestion, labelmodifreus, "labelmodifreus");
  GLADE_HOOKUP_OBJECT (windowgestion, label291, "label291");
  GLADE_HOOKUP_OBJECT (windowgestion, label293, "label293");
  GLADE_HOOKUP_OBJECT (windowgestion, label296, "label296");
  GLADE_HOOKUP_OBJECT (windowgestion, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (windowgestion, comboboxmodiftype, "comboboxmodiftype");
  GLADE_HOOKUP_OBJECT (windowgestion, comboboxmodifmarque, "comboboxmodifmarque");
  GLADE_HOOKUP_OBJECT (windowgestion, label294, "label294");
  GLADE_HOOKUP_OBJECT (windowgestion, label295, "label295");
  GLADE_HOOKUP_OBJECT (windowgestion, label275, "label275");
  GLADE_HOOKUP_OBJECT (windowgestion, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (windowgestion, scrolledwindow27, "scrolledwindow27");
  GLADE_HOOKUP_OBJECT (windowgestion, viewport2, "viewport2");
  GLADE_HOOKUP_OBJECT (windowgestion, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (windowgestion, treeview12, "treeview12");
  GLADE_HOOKUP_OBJECT (windowgestion, buttonaffichboard, "buttonaffichboard");
  GLADE_HOOKUP_OBJECT (windowgestion, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (windowgestion, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (windowgestion, image10, "image10");
  GLADE_HOOKUP_OBJECT (windowgestion, label310, "label310");
  GLADE_HOOKUP_OBJECT (windowgestion, label298, "label298");
  GLADE_HOOKUP_OBJECT (windowgestion, label276, "label276");

  return windowgestion;
}

